# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterprofile',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='twitterprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
