# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapi', '0002_auto_20170625_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('job', models.CharField(max_length=200, unique=True)),
                ('status', models.IntegerField(default=202)),
                ('twitter_response', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
