# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapi', '0003_twittertaskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertaskstatus',
            name='twitter_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
